from .ant import Ant
from .betta_fish import Betta_Fish
from .copperhead import Copperhead
from .earthworm import Earthworm
from .finch import Finch
from .gerbil import Gerbil
from .mouse import Mouse
from .parakeet import Parakeet
from .timber_rattlesnake import Timber_Rattlesnake
from .terrapin import Terrapin